{% set name = "proxyspy" %}
{% set version = "0.1.5" %}
{% set sha256 = "c130cc14b854d72930698558caa0affe6fa76840d3cd6a75b0ffc269939329e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]
  entry_points:
    - proxyspy = proxyspy:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - cryptography

test:
  imports:
    - proxyspy
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - requests
    - psutil
  commands:
    - pip check
    - proxyspy --help
    - pytest -v tests

about:
  home: https://github.com/anaconda/proxyspy
  summary: A debugging proxy that can log or intercept HTTPS requests
  description: |
    A single-file script for exercising HTTP/S client applications.
    A debugging proxy that can log or intercept HTTPS requests. This tool can be used to:

    - Monitor HTTPS traffic from applications
    - Debug SSL/TLS issues
    - Test applications against specific HTTP responses
    - Simulate network delays
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/anaconda/proxyspy
  doc_url: https://github.com/anaconda/proxyspy

extra:
  recipe-maintainers:
    - Jrice1317
    - mcg1969
